name: deploy

on:
    workflow_dispatch: {} # 手动触发
    push:
        branches:
            - main
        paths:
            - "docs/**" # 在 docs 目录下的文件发生变化时触发

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"

            - name: Install dependencies
              run: npm install

            - name: Generate vitepress
              run: npm run docs:build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.DEPLOY_SECRET }}
                  publish_dir: ./docs/.vitepress/dist
                  publish_branch: gh-pages
